import { SlideType, SLIDE_TYPE_LABELS, SLIDE_TYPE_CATEGORY } from "./types";

export interface SlideTypeConfig {
  type: SlideType;
  label: string;
  category: "question" | "quiz" | "interaction" | "content";
  icon: string;
  color: string;
  hasOptions: boolean;
  hasTimer: boolean;
  hasPoints: boolean;
  defaultOptions: () => string[];
  defaultContent: () => Record<string, unknown>;
  maxOptions?: number;
  minOptions?: number;
}

export const SLIDE_TYPE_CONFIGS: Record<SlideType, SlideTypeConfig> = {
  word_cloud: {
    type: "word_cloud",
    label: SLIDE_TYPE_LABELS.word_cloud,
    category: SLIDE_TYPE_CATEGORY.word_cloud,
    icon: "Cloud",
    color: "#FF6B6B",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({ maxResponseLength: 25, maxResponses: 5 }),
  },
  multiple_choice: {
    type: "multiple_choice",
    label: SLIDE_TYPE_LABELS.multiple_choice,
    category: SLIDE_TYPE_CATEGORY.multiple_choice,
    icon: "BarChart3",
    color: "#5A6BE6",
    hasOptions: true,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => ["Option 1", "Option 2", "Option 3"],
    defaultContent: () => ({}),
    minOptions: 2,
    maxOptions: 8,
  },
  open_ended: {
    type: "open_ended",
    label: SLIDE_TYPE_LABELS.open_ended,
    category: SLIDE_TYPE_CATEGORY.open_ended,
    icon: "MessageSquare",
    color: "#F19A9A",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({ maxResponseLength: 500 }),
  },
  scales: {
    type: "scales",
    label: SLIDE_TYPE_LABELS.scales,
    category: SLIDE_TYPE_CATEGORY.scales,
    icon: "SlidersHorizontal",
    color: "#8784DA",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({
      scaleMin: 1,
      scaleMax: 10,
      scaleMinLabel: "Low",
      scaleMaxLabel: "High",
    }),
  },
  ranking: {
    type: "ranking",
    label: SLIDE_TYPE_LABELS.ranking,
    category: SLIDE_TYPE_CATEGORY.ranking,
    icon: "GripVertical",
    color: "#58AF6C",
    hasOptions: true,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => ["Item 1", "Item 2", "Item 3", "Item 4"],
    defaultContent: () => ({}),
    minOptions: 2,
    maxOptions: 10,
  },
  hundred_points: {
    type: "hundred_points",
    label: SLIDE_TYPE_LABELS.hundred_points,
    category: SLIDE_TYPE_CATEGORY.hundred_points,
    icon: "CircleDot",
    color: "#3B82F6",
    hasOptions: true,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => ["Option 1", "Option 2", "Option 3"],
    defaultContent: () => ({ totalPoints: 100 }),
    minOptions: 2,
    maxOptions: 10,
  },
  two_by_two: {
    type: "two_by_two",
    label: SLIDE_TYPE_LABELS.two_by_two,
    category: SLIDE_TYPE_CATEGORY.two_by_two,
    icon: "Grid2x2",
    color: "#FF8A8A",
    hasOptions: true,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => ["Item 1", "Item 2", "Item 3"],
    defaultContent: () => ({ gridXLabel: "X Axis", gridYLabel: "Y Axis" }),
    minOptions: 2,
    maxOptions: 8,
  },
  pin_on_image: {
    type: "pin_on_image",
    label: SLIDE_TYPE_LABELS.pin_on_image,
    category: SLIDE_TYPE_CATEGORY.pin_on_image,
    icon: "MapPin",
    color: "#6156BB",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({ imageUrl: "" }),
  },
  qa: {
    type: "qa",
    label: SLIDE_TYPE_LABELS.qa,
    category: SLIDE_TYPE_CATEGORY.qa,
    icon: "HelpCircle",
    color: "#F3A0A0",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({}),
  },
  timer: {
    type: "timer",
    label: SLIDE_TYPE_LABELS.timer,
    category: SLIDE_TYPE_CATEGORY.timer,
    icon: "Clock",
    color: "#F5B531",
    hasOptions: false,
    hasTimer: true,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({ timerDuration: 60 }),
  },
  instructions: {
    type: "instructions",
    label: SLIDE_TYPE_LABELS.instructions,
    category: SLIDE_TYPE_CATEGORY.instructions,
    icon: "FileText",
    color: "#6B7280",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({
      instructionSteps: [
        "Go to inzphire.com",
        "Enter the code shown on screen",
      ],
    }),
  },
  content: {
    type: "content",
    label: SLIDE_TYPE_LABELS.content,
    category: SLIDE_TYPE_CATEGORY.content,
    icon: "File",
    color: "#9CA3AF",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({ contentHtml: "" }),
  },
  image_choice: {
    type: "image_choice",
    label: SLIDE_TYPE_LABELS.image_choice,
    category: SLIDE_TYPE_CATEGORY.image_choice,
    icon: "Image",
    color: "#3B82F6",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({ imageOptions: [] }),
  },
  select_answer_quiz: {
    type: "select_answer_quiz",
    label: SLIDE_TYPE_LABELS.select_answer_quiz,
    category: SLIDE_TYPE_CATEGORY.select_answer_quiz,
    icon: "CheckCircle",
    color: "#3B82F6",
    hasOptions: true,
    hasTimer: true,
    hasPoints: true,
    defaultOptions: () => ["Option A", "Option B", "Option C", "Option D"],
    defaultContent: () => ({
      quizPoints: 1000,
      quizTimerSeconds: 30,
      correctAnswerIndex: 0,
    }),
    minOptions: 2,
    maxOptions: 6,
  },
  type_answer_quiz: {
    type: "type_answer_quiz",
    label: SLIDE_TYPE_LABELS.type_answer_quiz,
    category: SLIDE_TYPE_CATEGORY.type_answer_quiz,
    icon: "Type",
    color: "#58AF6C",
    hasOptions: false,
    hasTimer: true,
    hasPoints: true,
    defaultOptions: () => [],
    defaultContent: () => ({
      quizPoints: 1000,
      quizTimerSeconds: 30,
      correctAnswers: [],
    }),
  },
  leaderboard: {
    type: "leaderboard",
    label: SLIDE_TYPE_LABELS.leaderboard,
    category: SLIDE_TYPE_CATEGORY.leaderboard,
    icon: "Trophy",
    color: "#F5B531",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({}),
  },
  reactions: {
    type: "reactions",
    label: SLIDE_TYPE_LABELS.reactions,
    category: SLIDE_TYPE_CATEGORY.reactions,
    icon: "Smile",
    color: "#8B5CF6",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({ reactions: ["👍", "❤️", "😂", "😮", "👏"] }),
  },
  quick_form: {
    type: "quick_form",
    label: SLIDE_TYPE_LABELS.quick_form,
    category: SLIDE_TYPE_CATEGORY.quick_form,
    icon: "ClipboardList",
    color: "#3B82F6",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({
      formFields: [
        { id: "email", label: "Email", type: "email" },
        { id: "name", label: "Name", type: "text" },
      ],
    }),
  },
  comments: {
    type: "comments",
    label: SLIDE_TYPE_LABELS.comments,
    category: SLIDE_TYPE_CATEGORY.comments,
    icon: "MessageCircle",
    color: "#14B8A6",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({}),
  },
  gather_names: {
    type: "gather_names",
    label: SLIDE_TYPE_LABELS.gather_names,
    category: SLIDE_TYPE_CATEGORY.gather_names,
    icon: "UserPlus",
    color: "#6366F1",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({}),
  },
  guess_number: {
    type: "guess_number",
    label: SLIDE_TYPE_LABELS.guess_number,
    category: SLIDE_TYPE_CATEGORY.guess_number,
    icon: "Hash",
    color: "#F97316",
    hasOptions: false,
    hasTimer: false,
    hasPoints: false,
    defaultOptions: () => [],
    defaultContent: () => ({
      correctNumber: 7,
      guessMin: 0,
      guessMax: 100,
    }),
  },
};

export const SLIDE_TYPES_BY_CATEGORY = {
  question: Object.keys(SLIDE_TYPE_CONFIGS).filter(
    (key) => SLIDE_TYPE_CONFIGS[key as SlideType].category === "question"
  ) as SlideType[],
  quiz: Object.keys(SLIDE_TYPE_CONFIGS).filter(
    (key) => SLIDE_TYPE_CONFIGS[key as SlideType].category === "quiz"
  ) as SlideType[],
  interaction: Object.keys(SLIDE_TYPE_CONFIGS).filter(
    (key) => SLIDE_TYPE_CONFIGS[key as SlideType].category === "interaction"
  ) as SlideType[],
  content: Object.keys(SLIDE_TYPE_CONFIGS).filter(
    (key) => SLIDE_TYPE_CONFIGS[key as SlideType].category === "content"
  ) as SlideType[],
};
